# -*- coding: utf-8 -*-
"""newton1D.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jOGz59xtxBKEGZqOYvq0RouaC4_MzMSf
"""

def f(x):
  return x**2 - 3*x + 2

def df(x):
  return 2*x - 3

def newton1D():
  # Guess solution
  x = 5

  # Tolerance
  eps = 1e-6

  # Error
  err = eps*10 # initialize to a value larger than eps

  while err > eps:
    deltaX = f(x) / df(x)
    x = x - deltaX
    err = abs(deltaX)

  return x

newton1D()